#!/usr/bin/env bash
#==========================================================================
#
#   Copyright Insight Software Consortium
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#          http://www.apache.org/licenses/LICENSE-2.0.txt
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
#==========================================================================*/

die() {
  echo 'gerrit-merge failure' 1>&2
  echo '--------------------' 1>&2
  echo '' 1>&2
  echo "$@" 1>&2
  exit 1
}

# Do not merge until it has been sent up to Gerrit for review.
gerrit_remote=$(git config remote.gerrit.url)
test $? -ne 0 && die "Gerrit remote not set."
gerrit_url=$(echo $gerrit_remote | cut -d ':' -f 1)
gerrit_project=$(echo $gerrit_remote | cut -d ':' -f 2)

ssh $gerrit_url gerrit ls-projects >/dev/null || die "Could not connect to Gerrit."

head_sha=$(git show-ref HEAD | cut -d ' ' -f 1)
approval=$(ssh $gerrit_url gerrit approve --project=${gerrit_project} $head_sha 2>&1)
if test -n "$approval"; then
  die "Unexpected approval output:

$approval

Have you pushed your patch to Gerrit for review (git gerrit-push)?"
fi

git stage-push && git stage-merge
