#!/usr/bin/env bash
#==========================================================================
#
#   Copyright Insight Software Consortium
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#          http://www.apache.org/licenses/LICENSE-2.0.txt
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
#==========================================================================

die() {
  echo 'gerrit-merge failure' 1>&2
  echo '--------------------' 1>&2
  echo '' 1>&2
  echo "$@" 1>&2
  exit 1
}

# Do not merge until it has been sent up to Gerrit for review.
gerrit_remote=$(git config remote.gerrit.url)
gerrit_push_url=$(git config remote.gerrit.pushurl)
if test -n "$gerrit_push_url"; then
  gerrit_url=$(echo $gerrit_push_url | cut -d ':' -f 1)
  gerrit_project=$(echo $gerrit_push_url | cut -d ':' -f 2)
elif test -n "$gerrit_remote"; then
  gerrit_url=$(echo $gerrit_remote | cut -d ':' -f 1)
  gerrit_project=$(echo $gerrit_remote | cut -d ':' -f 2)
else
  die "Git remote not set."
fi

ssh $gerrit_url gerrit ls-projects >/dev/null || die "Could not connect to Gerrit."

head_sha=$(git rev-parse HEAD)
commit_count=$(ssh $gerrit_url gerrit query -- commit:$head_sha | awk '/rowCount/ { print $2 }')
if test "$commit_count" -lt 1; then
  echo "Commit not found in Gerrit.

Have you pushed your patch-set to Gerrit for review (git gerrit-push)?

Attempting 'git gerrit-push'...
"

  git gerrit-push 2>&1 | tee push_output.txt
  grep -q 'no changes made' push_output.txt
  no_changes="$?"
  rm push_output.txt
  if test "$no_changes" -eq 0; then
    echo "cherry-pick detected causing commit to not be found in Gerrit.

Continuing with merge..."
  else
    die "Patch set was uploaded to gerrit.  If a merge is still desired, please
run 'git gerrit-merge' again."
  fi
fi

git stage-push && git stage-merge
