itk_module(ITK_IntegratedTest
  TEST_DEPENDS
    ITK_AnisotropicSmoothing
    ITK_AntiAlias
    ITK_BiasCorrection
    ITK_BioCell
    ITK_Blox
    ITK_Classifiers
    ITK_Common
    ITK_ConnectedComponents
    ITK_CurvatureFlow
    ITK_DeformableMesh
    ITK_DeformationField
    ITK_Deprecated
    ITK_DiffusionTensorImage
    ITK_DistanceMap
    ITK_Eigen
    ITK_FEM
    ITK_FEMRegistration
    ITK_FFT
    ITK_FiniteDifference
    ITK_ImageAdaptors
    ITK_ImageCompare
    ITK_ImageCompose
    ITK_ImageFeature
    ITK_ImageFilterBase
    ITK_ImageFunction
    ITK_ImageGradient
    ITK_ImageGrid
    ITK_ImageIntensity
    ITK_ImageLabel
    ITK_ImageStatistics
    ITK_IO_Base
    ITK_IO_BioRad
    ITK_IO_BMP
    ITK_IO_GDCM
    ITK_IO_GE
    ITK_IO_GIPL
    ITK_IO_IPL
    ITK_IO_JPEG
    ITK_IO_LSM
    ITK_IO_Meta
    ITK_IO_NIFTI
    ITK_IO_NRRD
    ITK_IO_PNG
    ITK_IO_RAW
    ITK_IO_Siemens
    ITK_IO_SpatialObjects
    ITK_IO_Stimulate
    ITK_IO_TIFF
    ITK_IO_VTK
    ITK_IO_XML
    ITK_KLMRegionGrowing
    ITK_LabelVoting
    ITK_LevelSets
    ITK_MarkovRandomFieldsClassifiers
    ITK_MathematicalMorphology
    ITK_Mesh
    ITK_NarrowBand
    ITK_NeuralNetworks
    ITK_Optimizers
    ITK_Path
    ITK_PDEDeformableRegistration
    ITK_Polynomials
    ITK_QuadEdgeMesh
    ITK_QuadEdgeMeshFiltering
    ITK_RegionGrowing
    ITK_RegistrationCommon
    ITK_SignedDistanceFunction
    ITK_Smoothing
    ITK_SpatialFunction
    ITK_SpatialObjects
    ITK_Statistics
    ITK_Thresholding
    ITK_Transform
    ITK_Voronoi
    ITK_VTK
    ITK_Watersheds
    ITK_TestKernel
)
