itk_module(ITK_LevelSets
  DEPENDS
    ITK_ImageFeature
    ITK_FiniteDifference
    ITK_DistanceMap
    ITK_SignedDistanceFunction
    ITK_AnisotropicSmoothing
    ITK_Thresholding
    ITK_Optimizers
    ITK_ImageCompare
    ITK_FastMarching
  TEST_DEPENDS
    ITK_TestKernel
)
