/*=========================================================================
 *
 *  Copyright Insight Software Consortium
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0.txt
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *=========================================================================*/
#if defined(_MSC_VER)
#pragma warning ( disable : 4786 )
#endif

#include <iostream>

#include "itkAddConstantToImageFilter.h"
#include "itkAggregateLabelMapFilter.hpp"
#include "itkAreaClosingImageFilter.h"
#include "itkAreaOpeningImageFilter.h"
#include "itkAtanRegularizedHeavisideStepFunction.h"
#include "itkAttributeKeepNObjectsLabelMapFilter.hpp"
#include "itkAttributeLabelObject.h"
#include "itkAttributeMorphologyBaseImageFilter.hpp"
#include "itkAttributeOpeningLabelMapFilter.hpp"
#include "itkAttributePositionLabelMapFilter.hpp"
#include "itkAttributeRelabelLabelMapFilter.hpp"
#include "itkAttributeSelectionLabelMapFilter.hpp"
#include "itkAttributeUniqueLabelMapFilter.hpp"
#include "itkAutoCropLabelMapFilter.hpp"
#include "itkAutumnColormapFunction.hpp"
#include "itkBinaryClosingByReconstructionImageFilter.hpp"
#include "itkBinaryContourImageFilter.hpp"
#include "itkBinaryFillholeImageFilter.hpp"
#include "itkBinaryGrindPeakImageFilter.hpp"
#include "itkBinaryImageToLabelMapFilter.hpp"
#include "itkBinaryImageToShapeLabelMapFilter.hpp"
#include "itkBinaryImageToStatisticsLabelMapFilter.hpp"
#include "itkBinaryMorphologicalClosingImageFilter.hpp"
#include "itkBinaryMorphologicalOpeningImageFilter.hpp"
#include "itkBinaryNotImageFilter.h"
#include "itkBinaryOpeningByReconstructionImageFilter.hpp"
#include "itkBinaryReconstructionByDilationImageFilter.hpp"
#include "itkBinaryReconstructionByErosionImageFilter.hpp"
#include "itkBinaryReconstructionLabelMapFilter.hpp"
#include "itkBinaryShapeKeepNObjectsImageFilter.hpp"
#include "itkBinaryShapeOpeningImageFilter.hpp"
#include "itkBinaryStatisticsKeepNObjectsImageFilter.hpp"
#include "itkBinaryStatisticsOpeningImageFilter.hpp"
#include "itkBlueColormapFunction.hpp"
#include "itkBoxMeanImageFilter.hpp"
#include "itkBoxSigmaImageFilter.hpp"
#include "itkBoxUtilities.h"
#include "itkBruker2DSEQImageIO.h"
#include "itkBruker2DSEQImageIOFactory.h"
#include "itkBSplineControlPointImageFilter.hpp"
#include "itkBSplineControlPointImageFunction.hpp"
#include "itkBSplineDeformableTransformInitializer.hpp"
#include "itkBSplineScatteredDataPointSetToImageFilter.hpp"
#include "itkChangeLabelLabelMapFilter.hpp"
#include "itkChangeRegionLabelMapFilter.hpp"
#include "itkColormapFunction.h"
#include "itkComplexBSplineInterpolateImageFunction.hpp"
#include "itkComposeRGBAImageFilter.h"
#include "itkCompositeTransform.hpp"
#include "itkConformalFlatteningMeshFilter.hpp"
#include "itkConstrainedRegionBasedLevelSetFunctionSharedData.h"
#include "itkContourExtractor2DImageFilter.hpp"
#include "itkConvolutionImageFilter.hpp"
#include "itkCoolColormapFunction.hpp"
#include "itkCopperColormapFunction.hpp"
#include "itkCoxDeBoorBSplineKernelFunction.hpp"
#include "itkCropLabelMapFilter.hpp"
#include "itkCustomColormapFunction.hpp"
#include "itkDeformationFieldTransform.hpp"
#include "itkDiffeomorphicDemonsRegistrationFilter.hpp"
#include "itkDirectFourierReconstructionImageToImageFilter.hpp"
#include "itkDiscreteGaussianDerivativeImageFilter.hpp"
#include "itkDiscreteGaussianDerivativeImageFunction.hpp"
#include "itkDiscreteGradientMagnitudeGaussianImageFunction.hpp"
#include "itkDiscreteHessianGaussianImageFunction.hpp"
#include "itkDivideByConstantImageFilter.h"
#include "itkESMDemonsRegistrationFunction.hpp"
#include "itkExponentialDeformationFieldImageFilter.hpp"
#include "itkFastApproximateRankImageFilter.h"
#include "itkFastSymmetricForcesDemonsRegistrationFilter.hpp"
#include "itkGaborImageSource.hpp"
#include "itkGaborKernelFunction.h"
#include "itkGaussianDerivativeOperator.hpp"
#include "itkGenericUtilities.h"
#include "itkGeometryUtilities.h"
#include "itkGreenColormapFunction.hpp"
#include "itkGreyColormapFunction.hpp"
#include "itkGridForwardWarpImageFilter.hpp"
#include "itkGridImageSource.hpp"
#include "itkHeavisideStepFunction.h"
#include "itkHeavisideStepFunctionBase.h"
#include "itkHessianToObjectnessMeasureImageFilter.hpp"
#include "itkHotColormapFunction.hpp"
#include "itkHSVColormapFunction.hpp"
#include "itkImageKernelOperator.hpp"
#include "itkImageToPathFilter.hpp"
#include "itkInPlaceLabelMapFilter.hpp"
#include "itkJetColormapFunction.hpp"
#include "itkJPEG2000ImageIO.h"
#include "itkJPEG2000ImageIOFactory.h"
#include "itkKappaSigmaThresholdImageCalculator.hpp"
#include "itkKappaSigmaThresholdImageFilter.hpp"
#include "itkLabelContourImageFilter.hpp"
#include "itkLabelGeometryImageFilter.hpp"
#include "itkLabelImageToLabelMapFilter.hpp"
#include "itkLabelImageToShapeLabelMapFilter.hpp"
#include "itkLabelImageToStatisticsLabelMapFilter.hpp"
#include "itkLabelMap.hpp"
#include "itkLabelMapContourOverlayImageFilter.hpp"
#include "itkLabelMapFilter.hpp"
#include "itkLabelMapMaskImageFilter.hpp"
#include "itkLabelMapOverlayImageFilter.hpp"
#include "itkLabelMapToAttributeImageFilter.hpp"
#include "itkLabelMapToBinaryImageFilter.hpp"
#include "itkLabelMapToLabelImageFilter.hpp"
#include "itkLabelMapToRGBImageFilter.hpp"
#include "itkLabelMapUtilities.h"
#include "itkLabelObject.hpp"
#include "itkLabelObjectAccessors.h"
#include "itkLabelObjectLine.hpp"
#include "itkLabelObjectLineComparator.h"
#include "itkLabelOverlayFunctor.h"
#include "itkLabelOverlayImageFilter.hpp"
#include "itkLabelSelectionLabelMapFilter.h"
#include "itkLabelShapeKeepNObjectsImageFilter.hpp"
#include "itkLabelShapeOpeningImageFilter.hpp"
#include "itkLabelStatisticsKeepNObjectsImageFilter.hpp"
#include "itkLabelStatisticsOpeningImageFilter.hpp"
#include "itkLabelToRGBFunctor.h"
#include "itkLabelToRGBImageFilter.hpp"
#include "itkLabelUniqueLabelMapFilter.h"
#include "itkMagnitudeAndPhaseToComplexImageFilter.h"
#include "itkMaskedMovingHistogramImageFilter.hpp"
#include "itkMaskedRankImageFilter.hpp"
#include "itkMergeLabelMapFilter.hpp"
#include "itkMiniPipelineSeparableImageFilter.hpp"
#include "itkMorphologicalWatershedFromMarkersImageFilter.hpp"
#include "itkMorphologicalWatershedImageFilter.hpp"
#include "itkMRCHeaderObject.h"
#include "itkMRCImageIO.h"
#include "itkMRCImageIOFactory.h"
#include "itkMultiphaseDenseFiniteDifferenceImageFilter.hpp"
#include "itkMultiphaseFiniteDifferenceImageFilter.hpp"
#include "itkMultiphaseSparseFiniteDifferenceImageFilter.hpp"
#include "itkMultiplyByConstantImageFilter.h"
#include "itkMultiScaleHessianBasedMeasureImageFilter.hpp"
#include "itkN4MRIBiasFieldCorrectionImageFilter.hpp"
#include "itkNeuralNetworkFileReader.hpp"
#include "itkNeuralNetworkFileWriter.hpp"
#include "itkObjectByObjectLabelMapFilter.hpp"
#include "itkObjectToObjectMetric.hpp"
#include "itkOverUnderColormapFunction.hpp"
#include "itkPadLabelMapFilter.hpp"
#include "itkPhilipsPAR.h"
#include "itkPhilipsRECImageIO.h"
#include "itkPhilipsRECImageIOFactory.h"
#include "itkRankHistogram.h"
#include "itkRankImageFilter.hpp"
#include "itkRealAndImaginaryToComplexImageFilter.h"
#include "itkRedColormapFunction.hpp"
#include "itkRegionalMaximaImageFilter.hpp"
#include "itkRegionalMinimaImageFilter.hpp"
#include "itkRegionBasedLevelSetFunction.hpp"
#include "itkRegionBasedLevelSetFunctionData.hpp"
#include "itkRegionBasedLevelSetFunctionSharedData.h"
#include "itkRegionFromReferenceLabelMapFilter.hpp"
#include "itkRegularizedHeavisideStepFunction.h"
#include "itkRelabelLabelMapFilter.h"
#include "itkRobustAutomaticThresholdCalculator.hpp"
#include "itkRobustAutomaticThresholdImageFilter.hpp"
#include "itkScalarChanAndVeseDenseLevelSetImageFilter.hpp"
#include "itkScalarChanAndVeseLevelSetFunction.hpp"
#include "itkScalarChanAndVeseLevelSetFunctionData.h"
#include "itkScalarChanAndVeseSparseLevelSetImageFilter.hpp"
#include "itkScalarRegionBasedLevelSetFunction.hpp"
#include "itkScalarToRGBColormapImageFilter.hpp"
#include "itkShapedFloodFilledFunctionConditionalConstIterator.hpp"
#include "itkShapedFloodFilledImageFunctionConditionalConstIterator.hpp"
#include "itkShapedFloodFilledImageFunctionConditionalIterator.h"
#include "itkShapeKeepNObjectsLabelMapFilter.hpp"
#include "itkShapeLabelMapFilter.hpp"
#include "itkShapeLabelObject.h"
#include "itkShapeLabelObjectAccessors.h"
#include "itkShapeOpeningLabelMapFilter.hpp"
#include "itkShapePositionLabelMapFilter.hpp"
#include "itkShapeRelabelImageFilter.hpp"
#include "itkShapeRelabelLabelMapFilter.hpp"
#include "itkShapeUniqueLabelMapFilter.hpp"
#include "itkShiftScaleLabelMapFilter.hpp"
#include "itkSinRegularizedHeavisideStepFunction.h"
#include "itkSliceBySliceImageFilter.hpp"
#include "itkSpringColormapFunction.hpp"
#include "itkStatisticsKeepNObjectsLabelMapFilter.hpp"
#include "itkStatisticsLabelMapFilter.hpp"
#include "itkStatisticsLabelObject.h"
#include "itkStatisticsLabelObjectAccessors.h"
#include "itkStatisticsOpeningLabelMapFilter.hpp"
#include "itkStatisticsPositionLabelMapFilter.hpp"
#include "itkStatisticsRelabelImageFilter.hpp"
#include "itkStatisticsRelabelLabelMapFilter.hpp"
#include "itkStatisticsUniqueLabelMapFilter.hpp"
#include "itkStochasticFractalDimensionImageFilter.hpp"
#include "itkSubtractConstantFromImageFilter.h"
#include "itkSummerColormapFunction.hpp"
#include "itkTransformToDeformationFieldSource.hpp"
#include "itkUnconstrainedRegionBasedLevelSetFunctionSharedData.h"
#include "itkValuedRegionalExtremaImageFilter.hpp"
#include "itkValuedRegionalMaximaImageFilter.h"
#include "itkValuedRegionalMinimaImageFilter.h"
#include "itkVectorCentralDifferenceImageFunction.hpp"
#include "itkVectorLinearInterpolateNearestNeighborExtrapolateImageFunction.hpp"
#include "itkVoxBoCUBImageIO.h"
#include "itkVoxBoCUBImageIOFactory.h"
#include "itkWarpHarmonicEnergyCalculator.hpp"
#include "itkWinterColormapFunction.hpp"



int itkReviewHeaderTest ( int , char * [] )
{

  return EXIT_SUCCESS;
}
