option(ITK_SUPPORTS_ANALYZE_IMAGEIO "Support the Analyze file format" ON)
option(ITK_SUPPORTS_BIORAD_IMAGEIO "Support the Biorad file format" ON)
option(ITK_SUPPORTS_BMP_IMAGEIO "Support the BMP file format" ON)
option(ITK_SUPPORTS_GDCM_IMAGEIO "Support the GDCM file format" ON)
option(ITK_SUPPORTS_GIPL_IMAGEIO "Support the GIPL file format" ON)
option(ITK_SUPPORTS_JPEG_IMAGEIO "Support the JPEG file format" ON)
option(ITK_SUPPORTS_LSM_IMAGEIO "Support the LSM file format" ON)
option(ITK_SUPPORTS_META_IMAGEIO "Support the META file format" ON)
option(ITK_SUPPORTS_NIFTI_IMAGEIO "Support the NIFTI file format" ON)
option(ITK_SUPPORTS_NRRD_IMAGEIO "Support the NRRD file format" ON)
option(ITK_SUPPORTS_PNG_IMAGEIO "Support the PNG file format" ON)
option(ITK_SUPPORTS_STIMULATE_IMAGEIO "Support the STIMULATE file format" ON)
option(ITK_SUPPORTS_TIFF_IMAGEIO "Support the TIFF file format" ON)
option(ITK_SUPPORTS_VTK_IMAGEIO "Support the VTK file format" ON)

mark_as_advanced(ITK_SUPPORTS_ANALYZE_IMAGEIO)
mark_as_advanced(ITK_SUPPORTS_BIORAD_IMAGEIO)
mark_as_advanced(ITK_SUPPORTS_BMP_IMAGEIO)
mark_as_advanced(ITK_SUPPORTS_GDCM_IMAGEIO)
mark_as_advanced(ITK_SUPPORTS_GIPL_IMAGEIO)
mark_as_advanced(ITK_SUPPORTS_JPEG_IMAGEIO)
mark_as_advanced(ITK_SUPPORTS_LSM_IMAGEIO)
mark_as_advanced(ITK_SUPPORTS_META_IMAGEIO)
mark_as_advanced(ITK_SUPPORTS_NIFTI_IMAGEIO)
mark_as_advanced(ITK_SUPPORTS_NRRD_IMAGEIO)
mark_as_advanced(ITK_SUPPORTS_PNG_IMAGEIO)
mark_as_advanced(ITK_SUPPORTS_STIMULATE_IMAGEIO)
mark_as_advanced(ITK_SUPPORTS_TIFF_IMAGEIO)
mark_as_advanced(ITK_SUPPORTS_VTK_IMAGEIO)
